### ISSUE TITLE
Multiple MAC

### ISSUE THREAD

**Issue by prasathn1984** [robschn/mac-change-vlan#3]
Hello Rob, 

Really your script is amazing and it is working well. 
how do we move multiple MAC addresses into same vlan by using your script. Could you help on this. I tried with "open", but it was not successful. please help on this.

Prasath

**Comment by robschn** [comment]
Heya Prasath, sorry for the delay. 

I'm not sure I understand the specific ask of your question. This script just finds all the devices with MAC addresses that match first three octets supplied by the user. The idea being that similar devices most likely go in the same VLAN. 

This was made during my automation learning so as a result makes alot of assumptions. I would be wary with running this outside of a learning environments.
